In [1]:
import pandas as pd

train =pd.read_csv('C:\\Users\\kimsj\\OneDrive\\바탕 화면\\대학교\\git\\AI-project\\data\\train.csv')
x_test =pd.read_csv('C:\\Users\\kimsj\\OneDrive\\바탕 화면\\대학교\\git\\AI-project\\data\\test.csv')

train

,index,QaA,QaE,QbA,QbE,QcA,QcE,QdA,QdE,QeA,...,wr_04,wr_05,wr_06,wr_07,wr_08,wr_09,wr_10,wr_11,wr_12,wr_13
0,43375,1.0,324,5.0,1067,5.0,359,1.0,709,1.0,...,1,1,1,1,1,0,1,0,1,1
1,4486,1.0,534,5.0,1555,5.0,2024,1.0,1097,1.0,...,1,1,1,1,1,0,1,0,1,1
2,10262,5.0,609,1.0,749,2.0,624,1.0,1833,3.0,...,1,1,0,1,1,0,1,0,1,0
3,14088,4.0,182,1.0,2969,1.0,1955,4.0,4630,1.0,...,0,1,0,1,1,0,1,0,1,1
4,13398,4.0,549,5.0,1679,5.0,481,3.0,595,1.0,...,1,1,0,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36420,16511,1.0,312,5.0,965,5.0,499,1.0,1188,1.0,...,1,1,0,1,1,0,1,1,1,1
36421,33507,3.0,474,4.0,1033,5.0,602,2.0,703,1.0,...,1,1,1,1,1,0,1,1,1,1
36422,44917,2.0,617,4.0,1262,2.0,709,1.0,1063,2.0,...,1,1,0,1,1,0,1,1,1,1
36423,36126,5.0,294,1.0,985,1.0,504,3.0,613,5.0,...,1,1,1,1,1,1,1,1,1,1
36424,42340,3.0,1062,1.0,3111,2.0,899,1.0,1876,3.0,...,1,1,1,1,1,1,1,1,1,1

In [2]:
from sklearn import preprocessing

def encode_features(dataDF):
    features = ["age_group","gender", "race", "religion"]
    for featue in features:
        le = preprocessing.LabelEncoder()
        le = le.fit(dataDF[featue])
        dataDF[featue] = le.transform(dataDF[featue])
        
    return dataDF

train = encode_features(train)
x_test = encode_features(x_test)

y_train = train["voted"]
x_train = train.drop('voted', axis=1)

In [3]:
def get_categoty_time(Q_time):
    cat = 0
    if Q_time <= 500 : cat = 0
    elif Q_time <= 1000 : cat = 1
    elif Q_time <= 2000 : cat = 2
    elif Q_time <= 3000 : cat = 3
    elif Q_time <= 4000 : cat = 4
    elif Q_time <= 5000 : cat = 5
    elif Q_time <= 6000 : cat = 6
    elif Q_time <= 7000 : cat = 7
    elif Q_time <= 8000 : cat = 8
    elif Q_time <= 9000 : cat = 9
    elif Q_time <=10000 : cat = 10
    elif Q_time <=15000 : cat = 11
    elif Q_time <=20000 : cat = 12
    else : Q_time = 13

    return cat

Q_times = ['QaE', 'QbE', 'QcE', 'QdE', 'QeE', 'QfE', 'QgE', 'QhE', 'QiE', 'QjE', 'QkE','QlE', 'QmE', 'QnE', 'QoE', 'QpE', 'QqE', 'QrE', 'QsE', 'QtE']

for Q_time in Q_times:
    train[Q_time] = train[Q_time].apply(lambda x : get_categoty_time(x))
    x_test[Q_time] = x_test[Q_time].apply(lambda x : get_categoty_time(x))

In [4]:
def get_categoty_age(age_num):
    num = age_num;
    if age_num == 0: num =7

    return num
train["age_group"] = train["age_group"].apply(lambda x : get_categoty_age(x))
x_test["age_group"] = x_test["age_group"].apply(lambda x : get_categoty_age(x))

In [5]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
train.sample(10)

,index,QaA,QaE,QbA,QbE,QcA,QcE,QdA,QdE,QeA,QeE,QfA,QfE,QgA,QgE,QhA,QhE,QiA,QiE,QjA,QjE,QkA,QkE,QlA,QlE,QmA,QmE,QnA,QnE,QoA,QoE,QpA,QpE,QqA,QqE,QrA,QrE,QsA,QsE,QtA,QtE,age_group,education,engnat,familysize,gender,hand,married,race,religion,tp01,tp02,tp03,tp04,tp05,tp06,tp07,tp08,tp09,tp10,urban,voted,wf_01,wf_02,wf_03,wr_01,wr_02,wr_03,wr_04,wr_05,wr_06,wr_07,wr_08,wr_09,wr_10,wr_11,wr_12,wr_13
8087,24,2.0,1,3.0,2,3.0,2,1.0,1,3.0,2,4.0,3,4.0,2,3.0,2,3.0,3,3.0,2,5.0,2,3.0,2,2.0,2,4.0,3,2.0,2,1.0,2,4.0,1,3.0,3,3.0,1,1.0,1,4,3,2,3,0,1,2,6,0,2,5,0,6,5,6,3,6,0,6,3,1,0,0,1,1,1,0,1,1,1,1,1,0,1,0,1,1
6300,41716,2.0,1,5.0,4,5.0,2,1.0,3,1.0,5,1.0,2,1.0,2,3.0,3,2.0,8,5.0,2,3.0,11,5.0,3,5.0,3,2.0,2,3.0,2,1.0,2,2.0,3,1.0,12,3.0,10,5.0,5,1,1,1,2,0,1,1,6,0,5,1,4,3,1,1,6,2,3,6,0,0,0,0,0,0,1,0,1,0,0,1,1,0,1,0,1,0
9951,20608,5.0,1,5.0,3,4.0,1,1.0,1,1.0,1,1.0,0,1.0,0,1.0,2,1.0,2,5.0,1,4.0,2,5.0,1,5.0,2,1.0,0,1.0,2,5.0,1,1.0,1,1.0,1,4.0,0,4.0,1,1,3,1,2,1,1,1,1,1,0,2,2,6,1,2,4,4,0,0,2,1,1,0,0,1,1,0,1,1,0,1,1,0,1,0,1,1
10622,29429,5.0,1,1.0,2,4.0,2,3.0,2,2.0,3,4.0,3,5.0,2,1.0,2,5.0,2,2.0,3,5.0,2,4.0,2,1.0,1,5.0,0,1.0,2,1.0,1,4.0,1,4.0,3,1.0,2,1.0,1,5,4,1,3,0,1,2,6,1,4,6,1,5,0,2,1,2,2,5,2,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1
7619,22121,1.0,0,4.0,1,4.0,1,1.0,1,2.0,2,2.0,1,4.0,1,1.0,1,5.0,3,3.0,1,4.0,1,5.0,1,4.0,1,1.0,0,1.0,1,2.0,1,1.0,0,2.0,1,3.0,0,4.0,1,1,2,2,5,1,1,1,6,1,1,1,3,5,0,6,2,1,2,4,2,1,0,0,0,1,1,0,1,1,1,1,1,0,1,0,1,1
33289,3773,1.0,0,5.0,1,5.0,0,1.0,1,1.0,1,1.0,0,1.0,0,5.0,2,2.0,2,5.0,0,1.0,1,5.0,2,5.0,4,1.0,0,5.0,1,5.0,1,2.0,1,1.0,1,5.0,0,5.0,5,1,1,1,2,1,1,1,6,10,2,3,0,2,0,6,1,1,5,6,2,0,1,1,0,1,1,0,1,1,1,1,1,0,1,0,1,1
19862,619,1.0,0,1.0,2,4.0,2,1.0,2,1.0,2,2.0,2,3.0,4,5.0,3,5.0,3,2.0,3,5.0,1,4.0,3,4.0,2,4.0,2,1.0,2,4.0,2,1.0,1,5.0,2,1.0,1,1.0,2,2,3,1,2,0,1,1,5,6,5,2,2,6,1,1,1,5,3,6,3,0,0,0,0,1,1,0,1,1,0,0,1,1,1,1,1,1
2978,30476,1.0,0,3.0,2,5.0,1,2.0,2,2.0,2,2.0,1,4.0,1,1.0,2,5.0,4,5.0,4,5.0,1,5.0,3,5.0,1,3.0,3,2.0,1,2.0,10,1.0,0,1.0,3,1.0,1,1.0,1,1,1,1,3,1,1,1,6,5,5,1,0,4,0,0,0,5,1,0,3,0,0,0,0,0,1,0,1,1,0,1,1,0,1,0,1,1
10436,34490,1.0,1,4.0,1,4.0,1,1.0,1,4.0,1,1.0,2,2.0,1,4.0,4,2.0,7,4.0,2,4.0,2,5.0,1,4.0,1,2.0,0,4.0,1,2.0,2,3.0,1,1.0,1,4.0,1,5.0,1,1,2,2,3,1,1,1,1,6,2,1,4,5,0,1,5,2,0,4,2,0,0,0,0,1,1,0,1,1,0,1,1,0,1,0,1,1
8536,3791,1.0,1,5.0,2,5.0,0,1.0,1,1.0,2,1.0,1,1.0,0,4.0,1,2.0,2,5.0,2,1.0,1,3.0,1,5.0,1,1.0,0,5.0,0,5.0,0,1.0,0,1.0,2,5.0,0,5.0,1,1,2,1,2,1,1,1,5,1,6,1,1,3,0,0,3,2,3,4,3,1,1,1,0,1,1,0,1,1,1,1,1,1,1,1,1,1

In [6]:
sum = 0
sum1 = 0

for i in range(36425):
    sum1 +=1
    if y_train[i] == 1:
        sum+=1
print(sum, sum1)
print(sum1/sum)

16507 36425
2.2066396074392682

In [7]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score

knn_clf = KNeighborsClassifier(n_neighbors=4)
rf_clf = RandomForestClassifier(n_estimators=100, random_state=0)
dt_clf = DecisionTreeClassifier(random_state=0)
ada_clf = AdaBoostClassifier(n_estimators=100, random_state=0)
lr_clf = LogisticRegression(random_state=0)
gb_clf = GradientBoostingClassifier(random_state=0)

In [8]:
import warnings
warnings.filterwarnings('ignore')

knn_clf.fit(x_train,y_train)
knn_pred = knn_clf.predict_proba(x_test)

In [9]:
rf_clf.fit(x_train,y_train)
rf_pred = rf_clf.predict_proba(x_test)

In [10]:
dt_clf.fit(x_train,y_train)
dt_pred = dt_clf.predict_proba(x_test)

In [11]:
lr_clf.fit(x_train,y_train)
lr_pred = lr_clf.predict_proba(x_test)

In [12]:
gb_clf.fit(x_train, y_train)
gb_pred = gb_clf.predict_proba(x_test)

In [13]:
#다양한 방법으로 한습한 데이터가 평균적으로 0.5이상 일 경우 0과 1의 비가 train데이터의 voted값의 0과 1일의 비가 비슷한 것을 확인
sum = 0
sum1 = 0
for i in range(9107):
    sum1 +=1
    if (knn_pred[i][1] + rf_pred[i][1] + dt_pred[i][1] + lr_pred[i][1] + gb_pred[i][1]) >=2.50:
        sum+=1
print(sum, sum1)
print(sum1/sum)

3515 9107
2.5908961593172117

In [14]:
#다양한 방법으로 한습한 데이터가 평균적으로 0.5이상 일 경우 num에 1추가, 아니면 num에 0추가
num = []
for i in range(9107):

    if (knn_pred[i][1] + rf_pred[i][1] + dt_pred[i][1] + lr_pred[i][1] + gb_pred[i][1]) >=2.50:
        num.append(1)
    else :num.append(0)

In [15]:
x_test["voted"] = num

In [16]:
x_test["voted"].tail(10)

9097    0
9098    0
9099    1
9100    0
9101    0
9102    0
9103    1
9104    0
9105    1
9106    1
Name: voted, dtype: int64